### ISSUE TITLE
error within the code

### ISSUE THREAD

**Issue by remymumoh** [John61590/OkCupidAndroid#1]
An error occurred while executing doInBackground()

```
> FATAL EXCEPTION: AsyncTask #1
>                                                                        Process: com.johnbohne.okcupid, PID: 15081
>                                                                        java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:325)
>                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
>                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                            at java.lang.Thread.run(Thread.java:761)
>                                                                         Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
>                                                                            at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6891)
>                                                                            at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1048)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
>                                                                            at android.view.View.requestLayout(View.java:19781)
>                                                                            at android.view.View.setFlags(View.java:11478)
>                                                                            at android.view.View.setVisibility(View.java:8069)
>                                                                            at android.widget.AdapterView.updateEmptyStatus(AdapterView.java:763)
>                                                                            at android.widget.AdapterView.setEmptyView(AdapterView.java:687)
>                                                                            at com.johnbohne.okcupid.MainActivityFragment.getPeople(MainActivityFragment.java:157)
>                                                                            at com.johnbohne.okcupid.MainActivityFragment$GetPersonInformation.doInBackground(MainActivityFragment.java:65)
>                                                                            at com.johnbohne.okcupid.MainActivityFragment$GetPersonInformation.doInBackground(MainActivityFragment.java:59)
>                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:305)
>                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)

```

**Comment by John61590** [comment]
Doesn't happen to me... what were you doing?

**Comment by remymumoh** [comment]
i imported the code the way it is, ddnt change a thing, when trying to run on emulator or android m on a device it crashes

**Comment by John61590** [comment]
Works for me on emulator. I changed the build tools and sdk versions today though so might want to check that out.

<img width="343" alt="screen shot 2017-02-19 at 8 27 26 pm" src="https://cloud.githubusercontent.com/assets/3664020/23112066/f5180a22-f6e1-11e6-8bce-84d62218fb6d.png">

**Comment by remymumoh** [comment]
the new update works like a charm. Thanks. I have a question, can you guide me on how the algorithm of creating the match works after users answer the question?

**Comment by John61590** [comment]
I don't know that. It is proprietary information I would believe. This just pulls it from the JSON file.
